[package]
name = "single_source_shortest_path_dag"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
topological_sort = { path = "../topological_sort" }